//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculadoraPlanDepsiones.Presentation.WCFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class PersonType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AutonomoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Autonomo {
            get {
                return this.AutonomoField;
            }
            set {
                if ((this.AutonomoField.Equals(value) != true)) {
                    this.AutonomoField = value;
                    this.RaisePropertyChanged("Autonomo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((this.EmpleadoField.Equals(value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Echo", ReplyAction="http://tempuri.org/IService/EchoResponse")]
        string Echo(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Echo", ReplyAction="http://tempuri.org/IService/EchoResponse")]
        System.Threading.Tasks.Task<string> EchoAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalculateDesgravacionInversion", ReplyAction="http://tempuri.org/IService/CalculateDesgravacionInversionResponse")]
        decimal CalculateDesgravacionInversion(CalculadoraPlanDepsiones.Presentation.WCFService.PersonType personType, decimal investment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalculateDesgravacionInversion", ReplyAction="http://tempuri.org/IService/CalculateDesgravacionInversionResponse")]
        System.Threading.Tasks.Task<decimal> CalculateDesgravacionInversionAsync(CalculadoraPlanDepsiones.Presentation.WCFService.PersonType personType, decimal investment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CalculadoraPlanDepsiones.Presentation.WCFService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CalculadoraPlanDepsiones.Presentation.WCFService.IService>, CalculadoraPlanDepsiones.Presentation.WCFService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Echo(int value) {
            return base.Channel.Echo(value);
        }
        
        public System.Threading.Tasks.Task<string> EchoAsync(int value) {
            return base.Channel.EchoAsync(value);
        }
        
        public decimal CalculateDesgravacionInversion(CalculadoraPlanDepsiones.Presentation.WCFService.PersonType personType, decimal investment) {
            return base.Channel.CalculateDesgravacionInversion(personType, investment);
        }
        
        public System.Threading.Tasks.Task<decimal> CalculateDesgravacionInversionAsync(CalculadoraPlanDepsiones.Presentation.WCFService.PersonType personType, decimal investment) {
            return base.Channel.CalculateDesgravacionInversionAsync(personType, investment);
        }
    }
}
